# Introduction to CUDA and PyCUDA

In [ ]:
!pip install pycuda # install cuda
import pycuda.driver as cuda
import pycuda.autoinit
from pycuda.compiler import SourceModule

In [ ]:
import numpy
numpy.random.seed(1729)
a = numpy.random.randn(4,4)

In [ ]:
a = a.astype(numpy.float32)

In [ ]:
a_gpu = cuda.mem_alloc(a.nbytes)

In [ ]:
cuda.memcpy_htod(a_gpu, a)


In [ ]:
mod = SourceModule("""
  __global__ void doublify(float *a)
  {
    int idx = threadIdx.x + threadIdx.y*4;
    a[idx] *= 2;
  }
  """)

In [ ]:
func = mod.get_function("doublify")
func(a_gpu, block=(4,4,1))

In [ ]:
a_doubled = numpy.empty_like(a)
cuda.memcpy_dtoh(a_doubled, a_gpu)
print(a_doubled)
print(a)

[[-1.3746789  -1.6419895   3.3047218  -1.1505861 ]
 [ 2.1979356   1.8518921  -1.9868276  -1.7164422 ]
 [ 0.14977352  1.058711    0.2419031  -0.44884723]
 [-3.113357    0.11188176  0.32294306 -4.2692833 ]]
[[-0.6873394  -0.82099473  1.6523609  -0.57529306]
 [ 1.0989678   0.92594606 -0.9934138  -0.8582211 ]
 [ 0.07488676  0.5293555   0.12095155 -0.22442362]
 [-1.5566785   0.05594088  0.16147153 -2.1346416 ]]


In [ ]:
b = numpy.random.randn(4,4)
b = b.astype(numpy.float32)
c = numpy.random.randn(4,4)
c = c.astype(numpy.float32)

In [ ]:
mod2 = SourceModule("""
  __global__ void add2(float *a, float *b)
  {
    int idx = threadIdx.x + threadIdx.y*4;
    a[idx] += b[idx];
  }
  """)

In [ ]:
b_gpu = cuda.mem_alloc(b.nbytes)
c_gpu = cuda.mem_alloc(c.nbytes)

cuda.memcpy_htod(b_gpu, b)
cuda.memcpy_htod(c_gpu, c)


In [ ]:
func = mod2.get_function("add2")
func(b_gpu,c_gpu, block=(4,4,1))

In [ ]:
added = numpy.empty_like(b)
cuda.memcpy_dtoh(added, b_gpu)
print(added)
print(b)
print(c)

[[-0.5257741   0.447586    1.5295702   0.39143866]
 [ 3.3902154  -2.549993   -1.6982892  -0.2884755 ]
 [-1.2885619  -1.2470585  -1.3161025   1.1179583 ]
 [-2.862448   -0.38533747 -0.0221602  -0.24921691]]
[[ 0.10967004  0.44301215  0.39626622  0.2497974 ]
 [ 1.2984973  -1.2804337  -0.97546583 -0.26908663]
 [-1.1057384  -0.1279927  -0.61782736 -0.98912627]
 [-2.8598924  -0.7943475  -0.30579695  1.7006376 ]]
[[-0.63544416  0.00457387  1.133304    0.14164127]
 [ 2.091718   -1.2695593  -0.7228234  -0.01938889]
 [-0.18282357 -1.1190658  -0.6982751   2.1070845 ]
 [-0.0025556   0.40901005  0.28363675 -1.9498545 ]]


# Exercises

1. Write a cuda kernel to find the elementwise square of a matrix
2. Write a cuda kernel to find a matrix, which when added to the given matrix results in every element being equal to zero
3. Write a cuda kernel to multiply two matrices:
    1. Assume square matrices, with dimensions < 1024
    2. Assume square matrices, with dimensions > 1024
    3. Assume non-square matrices, with dimensions > 1024

Вопрос первый

In [ ]:
mod3 = SourceModule("""
  __global__ void square2(float *a, int size)
  {
    int idx = threadIdx.x + threadIdx.y*size;
    a[idx] *= a[idx];
  }
  """)

In [ ]:
size = 7

numpy.random.seed(945)
d = numpy.random.randn(size,size)
d = d.astype(numpy.float32)

In [ ]:
d_gpu = cuda.mem_alloc(d.nbytes)
cuda.memcpy_htod(d_gpu, d)

In [ ]:
func = mod3.get_function("square2")
func(d_gpu, numpy.int32(size), block=(size,size,1))

In [ ]:
squared = numpy.empty_like(d)
cuda.memcpy_dtoh(squared, d_gpu)

In [ ]:
#print(d)
#print(squared)

print(numpy.max(numpy.abs(squared - d*d)))

0.0


Вопрос второй

In [ ]:
mod4 = SourceModule("""
  __global__ void minus(float *a, int size)
  {
    int idx = threadIdx.x + threadIdx.y*size;
    a[idx] = -a[idx];
  }
  """)

In [ ]:
size = 7

numpy.random.seed(9574)
d = numpy.random.randn(size,size)
d = d.astype(numpy.float32)

In [ ]:
d_gpu = cuda.mem_alloc(d.nbytes)
cuda.memcpy_htod(d_gpu, d)

In [ ]:
func = mod4.get_function("minus")
func(d_gpu, numpy.int32(size), block=(size,size,1))

In [ ]:
complement = numpy.empty_like(d)
cuda.memcpy_dtoh(complement, d_gpu)

In [ ]:
#print(d)
#print(complement)

print(numpy.max(numpy.abs(d + complement)))

0.0


Вопрос третий
A

In [ ]:
mod5 = SourceModule("""
  __global__ void multiplyA(float *a, float *b, float *c, int size)
  {
    int row = threadIdx.x;
    int col = threadIdx.y;

    c[col + row * size] = 0;
    for(int i=0; i<size; ++i){
        c[col + row * size] += a[i + row * size] * b[col + i * size];
    }
  }
  """)

In [ ]:
size = 8

numpy.random.seed(9574)

a = numpy.random.randn(size,size)
a = a.astype(numpy.float32)

b = numpy.random.randn(size,size)
b = b.astype(numpy.float32)

c = numpy.empty_like(a)
c = c.astype(numpy.float32)

In [ ]:
a_gpu = cuda.mem_alloc(a.nbytes)
cuda.memcpy_htod(a_gpu, a)

b_gpu = cuda.mem_alloc(b.nbytes)
cuda.memcpy_htod(b_gpu, b)

c_gpu = cuda.mem_alloc(c.nbytes)

In [ ]:
func = mod5.get_function("multiplyA")
func(a_gpu, b_gpu, c_gpu, numpy.int32(size), block=(size,size,1))

In [ ]:
cuda.memcpy_dtoh(c, c_gpu)

In [ ]:
#print(a@b)
#print(c)

print(numpy.max(numpy.abs(c - a@b)))

B

In [ ]:
mod6 = SourceModule("""
  __global__ void multiplyB(float *a, float *b, float *c, int size)
  {
    int row = threadIdx.x + blockDim.x * blockIdx.x;
    int col = threadIdx.y + blockDim.y * blockIdx.y;

    if (row < size && col < size){
        c[col + row * size] = 0;
        for(int i=0; i<size; ++i){
            c[col + row * size] += a[i + row * size] * b[col + i * size];
        }
    }
  }
  """)

In [ ]:
size = 56

numpy.random.seed(494)

a = numpy.random.randn(size,size)
a = a.astype(numpy.float32)

b = numpy.random.randn(size,size)
b = b.astype(numpy.float32)

c = numpy.empty_like(a)
c = c.astype(numpy.float32)

In [ ]:
a_gpu = cuda.mem_alloc(a.nbytes)
cuda.memcpy_htod(a_gpu, a)

b_gpu = cuda.mem_alloc(b.nbytes)
cuda.memcpy_htod(b_gpu, b)

c_gpu = cuda.mem_alloc(c.nbytes)

In [ ]:
block_size = 32
grid_size = (size + block_size - 1)

In [ ]:
func = mod6.get_function("multiplyB")
func(a_gpu, b_gpu, c_gpu, numpy.int32(size), block=(block_size,block_size,1), grid=(grid_size,grid_size,1))

In [ ]:
cuda.memcpy_dtoh(c, c_gpu)

In [ ]:
#print(a@b)
#print(c)

print(numpy.max(numpy.abs(c - a@b)))

C

In [ ]:
mod7 = SourceModule("""
  __global__ void multiplyC(float *a, float *b, float *c, int n, int m, int p)
  {
    int row = threadIdx.x + blockDim.x * blockIdx.x;
    int col = threadIdx.y + blockDim.y * blockIdx.y;

    if (row < n && col < m){
        c[col + row * m] = 0;
        for(int i=0; i<p; ++i){
            c[col + row * m] += a[i + row * p] * b[col + i * m];
        }
    }
  }
  """)

In [ ]:
n = 36
p = 48
m = 72

numpy.random.seed(5867)

a = numpy.random.randn(n,p)
a = a.astype(numpy.float32)

b = numpy.random.randn(p,m)
b = b.astype(numpy.float32)

c = numpy.zeros([n,m])
c = c.astype(numpy.float32)

In [ ]:
a_gpu = cuda.mem_alloc(a.nbytes)
cuda.memcpy_htod(a_gpu, a)

b_gpu = cuda.mem_alloc(b.nbytes)
cuda.memcpy_htod(b_gpu, b)

c_gpu = cuda.mem_alloc(c.nbytes)

In [ ]:
block_size_x = min(n, 32)
grid_size_x = (n + block_size_x - 1) // block_size_x

block_size_y = min(m, 32)
grid_size_y = (m + block_size_y - 1) // block_size_y

In [ ]:
func = mod7.get_function("multiplyC")
func(a_gpu, b_gpu, c_gpu,
     numpy.int32(n), numpy.int32(m), numpy.int32(p),
     block=(block_size_x,block_size_y,1), grid=(grid_size_x,grid_size_y,1))

In [ ]:
cuda.memcpy_dtoh(c, c_gpu)

In [ ]:
#print(a@b)
#print(c)

print(numpy.max(numpy.abs(c - a@b)))